{% set name = 'clorm' %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/potassco/{{ name }}.git

requirements:
  build:
    - clingo >=5.3.0
    - python >=3.5
    - setuptools
  run:
    - clingo >=5.3.0
    - python >=3.5

build:
  noarch: python
  script:
    - python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - clorm

about:
  home:  https://github/github.com/potassco/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ORM interface for the Clingo ASP Solver
  doc_url: https://github.com/potassco/{{ name }}
  dev_url: https://github.com/potassco/{{ name }}
